# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  type: server_db
  url: http://40.77.61.29:7474
  pool: 5
  timeout: 5000

test:
  type: server_db
  database: http://40.77.61.29:7475
  pool: 5
  timeout: 5000
